// ===== Default Lessons Data =====
const defaultLessonsData = [
  { id:'basic-electrical', title:'Basic Electrical Theory', titleHi:'बुनियादी विद्युत सिद्धांत', description:'Voltage, Current, Resistance basics', descHi:'वोल्टेज, करंट, प्रतिरोध की मूल बातें', topicId:'basic-electrical', videoUrl:'', pdfUrl:'', imageUrl:'',
    notes:'<h3>⚡ Basic Electrical Theory</h3><p><b>Voltage (V):</b> The electrical pressure that pushes current through a circuit. Measured in Volts (V). Think of it like water pressure in a pipe.</p><p><b>Current (I):</b> The flow of electrons through a conductor. Measured in Amperes (A). Like the flow rate of water.</p><p><b>Resistance (R):</b> Opposition to current flow. Measured in Ohms (Ω). Like the pipe size restricting water flow.</p><h4>Key Formulas:</h4><ul><li>V = I × R (Ohm\'s Law)</li><li>P = V × I (Power)</li><li>P = I² × R</li><li>P = V² / R</li></ul><h4>Types of Current:</h4><ul><li><b>DC (Direct Current):</b> Flows in one direction. Example: Battery</li><li><b>AC (Alternating Current):</b> Changes direction periodically. Example: Home supply (230V, 50Hz)</li></ul><h4>Conductors vs Insulators:</h4><ul><li><b>Conductors:</b> Copper, Aluminium, Silver, Gold</li><li><b>Insulators:</b> Rubber, Glass, Plastic, Mica, Porcelain</li></ul>'
  },
  { id:'ohms-law', title:"Ohm's Law", titleHi:'ओम का नियम', description:'V = IR and its applications', descHi:'V = IR और इसके अनुप्रयोग', topicId:'ohms-law', videoUrl:'', pdfUrl:'', imageUrl:'',
    notes:'<h3>📐 Ohm\'s Law</h3><p><b>Statement:</b> At constant temperature, the current flowing through a conductor is directly proportional to the voltage across it.</p><p><b>Formula: V = I × R</b></p><h4>Ohm\'s Law Triangle:</h4><ul><li>V = I × R (Find Voltage)</li><li>I = V / R (Find Current)</li><li>R = V / I (Find Resistance)</li></ul><h4>Solved Examples:</h4><p><b>Q1:</b> A 12V battery drives current through a 4Ω resistor. Find current.<br><b>Ans:</b> I = V/R = 12/4 = <b>3 Ampere</b></p><p><b>Q2:</b> Current of 5A flows through 10Ω resistance. Find voltage.<br><b>Ans:</b> V = IR = 5×10 = <b>50 Volts</b></p><h4>Resistivity (ρ):</h4><p>R = ρ × L / A<br>Where L = length, A = cross-sectional area</p><h4>Factors Affecting Resistance:</h4><ul><li>Length (more length = more R)</li><li>Area (more area = less R)</li><li>Material type</li><li>Temperature</li></ul>'
  },
  { id:'ac-dc', title:'AC/DC Circuits', titleHi:'AC/DC सर्किट', description:'Alternating & Direct current circuits', descHi:'प्रत्यावर्ती और दिष्ट धारा परिपथ', topicId:'ac-dc', videoUrl:'', pdfUrl:'', imageUrl:'',
    notes:'<h3>🔄 AC/DC Circuits</h3><h4>DC Circuits:</h4><ul><li>Series Circuit: R_total = R1 + R2 + R3</li><li>Parallel Circuit: 1/R_total = 1/R1 + 1/R2 + 1/R3</li><li>Kirchhoff\'s Current Law (KCL): Sum of currents at a node = 0</li><li>Kirchhoff\'s Voltage Law (KVL): Sum of voltages in a loop = 0</li></ul><h4>AC Circuits:</h4><ul><li><b>Frequency (f):</b> 50 Hz in India</li><li><b>Peak Value:</b> Maximum value of AC wave</li><li><b>RMS Value:</b> V_rms = V_peak / √2 = 0.707 × V_peak</li><li><b>India supply:</b> 230V RMS (peak ≈ 325V)</li></ul><h4>Three Phase Supply:</h4><ul><li>3 phases: R, Y, B (120° apart)</li><li>Line Voltage = √3 × Phase Voltage</li><li>Star Connection: V_L = √3 × V_Ph</li><li>Delta Connection: I_L = √3 × I_Ph</li></ul><h4>Power in AC:</h4><ul><li>Active Power (P) = VI cos φ (Watts)</li><li>Reactive Power (Q) = VI sin φ (VAR)</li><li>Apparent Power (S) = VI (VA)</li><li>Power Factor = cos φ</li></ul>'
  },
  { id:'wiring', title:'Wiring Diagrams', titleHi:'वायरिंग आरेख', description:'House wiring and industrial wiring', descHi:'घरेलू और औद्योगिक वायरिंग', topicId:'wiring', videoUrl:'', pdfUrl:'', imageUrl:'',
    notes:'<h3>🏠 Wiring Systems</h3><h4>Types of House Wiring:</h4><ol><li><b>Cleat Wiring:</b> Temporary, uses porcelain cleats</li><li><b>Casing Capping:</b> Uses wooden/PVC casing</li><li><b>Conduit Wiring:</b> Surface or concealed, most common</li><li><b>Batten Wiring:</b> Wires on wooden battens</li></ol><h4>Wire Color Code (India):</h4><ul><li>🔴 Red / Brown = Phase (Live)</li><li>⚫ Black / Blue = Neutral</li><li>🟢 Green / Green-Yellow = Earth</li></ul><h4>Common Circuits:</h4><ul><li><b>One-way switch:</b> Controls light from one point</li><li><b>Two-way switch:</b> Controls light from two points (staircase)</li><li><b>Intermediate switch:</b> Controls from three+ points</li><li><b>Series test lamp:</b> For testing continuity</li></ul><h4>Cable Sizes:</h4><ul><li>Lighting: 1.5 sq mm</li><li>Power socket: 2.5 sq mm</li><li>AC/Geyser: 4 sq mm</li><li>Main line: 6-10 sq mm</li></ul>'
  },
  { id:'motor', title:'Motor Winding', titleHi:'मोटर वाइंडिंग', description:'Single & three phase motor winding', descHi:'सिंगल और थ्री फेज मोटर वाइंडिंग', topicId:'motor', videoUrl:'', pdfUrl:'', imageUrl:'',
    notes:'<h3>⚙️ Motor Winding</h3><h4>Types of Motors:</h4><ul><li><b>Single Phase:</b> Capacitor start, capacitor run, split phase</li><li><b>Three Phase:</b> Squirrel cage, slip ring induction motor</li><li><b>DC Motors:</b> Series, shunt, compound</li></ul><h4>Winding Terms:</h4><ul><li><b>Coil:</b> One or more turns of wire</li><li><b>Slot:</b> Groove in stator/rotor to hold winding</li><li><b>Pole:</b> North or South magnetic pole</li><li><b>Pitch:</b> Distance between coil sides</li></ul><h4>Speed Formula:</h4><p>N = 120f / P<br>N = RPM, f = frequency (50Hz), P = number of poles</p><ul><li>2 pole = 3000 RPM</li><li>4 pole = 1500 RPM</li><li>6 pole = 1000 RPM</li></ul><h4>Motor Faults:</h4><ul><li>Burnt winding → Rewinding needed</li><li>Bearing failure → Replace bearings</li><li>Humming sound → Check capacitor/winding</li><li>Low speed → Check voltage, capacitor</li></ul>'
  },
  { id:'safety', title:'Electrical Safety', titleHi:'विद्युत सुरक्षा', description:'Safety practices and earthing', descHi:'सुरक्षा अभ्यास और अर्थिंग', topicId:'safety', videoUrl:'', pdfUrl:'', imageUrl:'',
    notes:'<h3>🛡️ Electrical Safety</h3><h4>Electric Shock Effects:</h4><ul><li>1 mA: Slight tingling</li><li>10-20 mA: Muscular contraction</li><li>50 mA: Pain, difficulty breathing</li><li>100-300 mA: Heart fibrillation (fatal)</li></ul><h4>Safety Rules:</h4><ol><li>Always switch OFF before working</li><li>Use insulated tools</li><li>Wear rubber gloves and shoes</li><li>Use voltage tester before touching wires</li><li>Never work on wet surfaces</li><li>Use LOTO (Lock Out Tag Out)</li></ol><h4>Protective Devices:</h4><ul><li><b>MCB:</b> Miniature Circuit Breaker</li><li><b>ELCB/RCCB:</b> Earth Leakage / Residual Current Device</li><li><b>Fuse:</b> Rewirable and HRC types</li></ul><h4>First Aid for Electric Shock:</h4><ol><li>Switch off power source</li><li>Separate victim using dry wood/rubber</li><li>Check breathing, give CPR if needed</li><li>Call emergency services</li></ol>'
  },
  { id:'transformer', title:'Transformer', titleHi:'ट्रांसफार्मर', description:'Types, working principle, losses', descHi:'प्रकार, कार्य सिद्धांत, हानियाँ', topicId:'transformer', videoUrl:'', pdfUrl:'', imageUrl:'',
    notes:'<h3>🔌 Transformer</h3><p><b>Principle:</b> Works on electromagnetic induction (Faraday\'s Law). Transfers electrical energy between circuits through magnetic coupling.</p><h4>Types:</h4><ul><li><b>Step-Up:</b> Increases voltage (N2 > N1)</li><li><b>Step-Down:</b> Decreases voltage (N2 < N1)</li><li><b>Isolation:</b> Same voltage, electrical isolation</li><li><b>Auto-transformer:</b> Single winding, tapped</li></ul><h4>Formula:</h4><p>V1/V2 = N1/N2 = I2/I1</p><p>Turns Ratio (k) = N2/N1</p><h4>Losses:</h4><ul><li><b>Copper Loss (I²R):</b> Heat in windings</li><li><b>Iron/Core Loss:</b> Hysteresis + Eddy current loss</li><li><b>Efficiency:</b> η = Output / Input × 100%</li></ul><h4>Parts:</h4><ul><li>Core (CRGO silicon steel)</li><li>Primary & Secondary windings</li><li>Tank, cooling oil, bushings, tap changer</li></ul>'
  },
  { id:'electrical-tools', title:'Electrical Tools', titleHi:'विद्युत उपकरण', description:'Hand tools, power tools, measuring instruments', descHi:'हैंड टूल, पावर टूल, मापक यंत्र', topicId:'electrical-tools', videoUrl:'', pdfUrl:'', imageUrl:'',
    notes:'<h3>🔧 Electrical Tools</h3><h4>Hand Tools:</h4><ul><li><b>Screwdriver:</b> Flat, Phillips, line tester</li><li><b>Pliers:</b> Combination, nose, side cutting</li><li><b>Wire stripper:</b> Removes insulation</li><li><b>Crimping tool:</b> For lugs and connectors</li><li><b>Hacksaw:</b> Cutting conduit/cables</li><li><b>Hammer:</b> Ball peen, claw hammer</li></ul><h4>Measuring Instruments:</h4><ul><li><b>Multimeter:</b> Measures V, I, R</li><li><b>Clamp Meter:</b> Measures current without breaking circuit</li><li><b>Megger:</b> Insulation resistance tester</li><li><b>Tachometer:</b> Measures RPM</li><li><b>Lux Meter:</b> Light intensity</li><li><b>Earth Tester:</b> Earth resistance</li></ul><h4>Power Tools:</h4><ul><li>Drill machine</li><li>Angle grinder</li><li>Soldering iron</li></ul>'
  },
  { id:'earthing', title:'Earthing & Grounding', titleHi:'अर्थिंग और ग्राउंडिंग', description:'Types of earthing, IS standards', descHi:'अर्थिंग के प्रकार, IS मानक', topicId:'earthing', videoUrl:'', pdfUrl:'', imageUrl:'',
    notes:'<h3>🔌 Earthing & Grounding</h3><p><b>Purpose:</b> To provide a safe path for fault current to flow to earth, protecting humans and equipment.</p><h4>Types of Earthing:</h4><ol><li><b>Pipe Earthing:</b> GI pipe buried in ground with salt+charcoal</li><li><b>Plate Earthing:</b> Copper/GI plate buried underground</li><li><b>Rod Earthing:</b> Copper rod driven into ground</li><li><b>Strip Earthing:</b> Metal strip buried horizontally</li></ol><h4>Earth Resistance Values:</h4><ul><li>Power station: < 0.5Ω</li><li>Substation: < 1Ω</li><li>House: < 5Ω</li><li>Lightning arrester: < 2Ω</li></ul><h4>Components:</h4><ul><li>Earth electrode (pipe/plate/rod)</li><li>Earth wire (green)</li><li>Salt + Charcoal (moisture retention)</li><li>Earth pit with CI cover</li></ul>'
  },
  { id:'batteries', title:'Batteries & Cells', titleHi:'बैटरी और सेल', description:'Primary, secondary cells, maintenance', descHi:'प्राथमिक, द्वितीयक सेल, रखरखाव', topicId:'batteries', videoUrl:'', pdfUrl:'', imageUrl:'',
    notes:'<h3>🔋 Batteries & Cells</h3><h4>Primary Cells (Non-rechargeable):</h4><ul><li><b>Dry Cell:</b> 1.5V, zinc-carbon (torch, remote)</li><li><b>Alkaline Cell:</b> 1.5V, longer life</li><li><b>Lithium Cell:</b> 3V, button cells</li></ul><h4>Secondary Cells (Rechargeable):</h4><ul><li><b>Lead Acid:</b> 2V/cell, used in vehicles/UPS/inverters</li><li><b>Lithium Ion:</b> 3.7V/cell, phones/laptops</li><li><b>Nickel Cadmium:</b> 1.2V/cell, power tools</li></ul><h4>Lead Acid Battery Maintenance:</h4><ol><li>Check electrolyte level (add distilled water)</li><li>Specific gravity check (1.28 = full, 1.15 = discharged)</li><li>Clean terminals, apply petroleum jelly</li><li>Avoid overcharging/deep discharging</li></ol><h4>Series vs Parallel:</h4><ul><li><b>Series:</b> Voltage adds up (12V+12V = 24V)</li><li><b>Parallel:</b> Capacity adds up (same voltage, more Ah)</li></ul>'
  },
  { id:'capacitor', title:'Capacitors', titleHi:'कैपेसिटर', description:'Types, charging, discharging, uses', descHi:'प्रकार, चार्जिंग, डिस्चार्जिंग, उपयोग', topicId:'capacitor', videoUrl:'', pdfUrl:'', imageUrl:'',
    notes:'<h3>📦 Capacitors</h3><p><b>Definition:</b> A device that stores electrical energy in an electric field. Unit: Farad (F).</p><h4>Formula:</h4><p>C = Q/V (Capacitance = Charge/Voltage)</p><p>Energy = ½CV²</p><h4>Types:</h4><ul><li><b>Electrolytic:</b> Polarized, high capacitance (1µF-10000µF)</li><li><b>Ceramic:</b> Small, non-polarized (pF to µF)</li><li><b>Paper/Film:</b> Medium range</li><li><b>Fan Capacitor:</b> 2.5µF-4µF, oil-filled</li><li><b>Motor Start:</b> 50-300µF, used for starting torque</li><li><b>Motor Run:</b> 5-50µF, continuous duty</li></ul><h4>Connections:</h4><ul><li><b>Series:</b> 1/C_total = 1/C1 + 1/C2</li><li><b>Parallel:</b> C_total = C1 + C2 + C3</li></ul><h4>Uses in Electrician Trade:</h4><ul><li>Power factor correction</li><li>Motor starting</li><li>Fan speed control (capacitor regulator)</li><li>Filtering in power supply</li></ul>'
  },
  { id:'semiconductor', title:'Semiconductors & Diodes', titleHi:'अर्धचालक और डायोड', description:'PN junction, rectifiers, LED', descHi:'PN जंक्शन, रेक्टिफायर, LED', topicId:'semiconductor', videoUrl:'', pdfUrl:'', imageUrl:'',
    notes:'<h3>💡 Semiconductors & Diodes</h3><h4>Semiconductor Materials:</h4><ul><li><b>Silicon (Si):</b> Most common</li><li><b>Germanium (Ge):</b> Older devices</li><li>N-type: Extra electrons (doped with Phosphorus)</li><li>P-type: Extra holes (doped with Boron)</li></ul><h4>Diode:</h4><p>PN junction device. Allows current in one direction only.</p><ul><li>Forward Bias: Conducts (Si: 0.7V, Ge: 0.3V)</li><li>Reverse Bias: Blocks current</li></ul><h4>Types of Diodes:</h4><ul><li><b>Rectifier Diode:</b> AC to DC conversion</li><li><b>Zener Diode:</b> Voltage regulation</li><li><b>LED:</b> Light Emitting Diode</li><li><b>Photodiode:</b> Light detection</li></ul><h4>Rectifiers:</h4><ul><li><b>Half-wave:</b> Uses 1 diode, output = 0.45 × Vrms</li><li><b>Full-wave (Bridge):</b> Uses 4 diodes, output = 0.9 × Vrms</li></ul>'
  },
  { id:'electrical-machines', title:'Electrical Machines', titleHi:'विद्युत मशीनें', description:'Generators, alternators, starters', descHi:'जनरेटर, अल्टरनेटर, स्टार्टर', topicId:'electrical-machines', videoUrl:'', pdfUrl:'', imageUrl:'',
    notes:'<h3>🏭 Electrical Machines</h3><h4>DC Generator:</h4><p>Converts mechanical energy to DC electrical energy using electromagnetic induction.</p><ul><li>Parts: Armature, field winding, commutator, brushes</li><li>EMF formula: E = PΦNZ / 60A</li></ul><h4>Alternator (AC Generator):</h4><ul><li>Produces AC power</li><li>Used in power plants, DG sets</li><li>Frequency = PN/120</li></ul><h4>Motor Starters:</h4><ul><li><b>DOL (Direct On Line):</b> For motors < 5HP</li><li><b>Star-Delta:</b> For motors > 5HP, reduces starting current by 1/3</li><li><b>Auto-transformer:</b> Variable voltage starting</li><li><b>VFD:</b> Variable Frequency Drive for speed control</li></ul><h4>Motor Protection:</h4><ul><li>Overload relay (OLR)</li><li>Single phasing preventer</li><li>MCB/MCCB</li></ul>'
  },
  { id:'plc-basics', title:'PLC Basics', titleHi:'PLC की मूल बातें', description:'Introduction to programmable logic controllers', descHi:'प्रोग्रामेबल लॉजिक कंट्रोलर का परिचय', topicId:'plc-basics', videoUrl:'', pdfUrl:'', imageUrl:'',
    notes:'<h3>🖥️ PLC Basics</h3><p><b>PLC</b> = Programmable Logic Controller. A digital computer used for automation of industrial processes.</p><h4>Parts of PLC:</h4><ul><li><b>CPU:</b> Processor that executes program</li><li><b>Input Module:</b> Receives signals from sensors/switches</li><li><b>Output Module:</b> Sends signals to motors/actuators</li><li><b>Power Supply:</b> 24V DC typically</li><li><b>Programming Device:</b> Laptop with software</li></ul><h4>Programming Languages:</h4><ul><li><b>Ladder Logic:</b> Most common, looks like relay circuit</li><li><b>FBD:</b> Function Block Diagram</li><li><b>ST:</b> Structured Text</li></ul><h4>Common PLC Brands:</h4><ul><li>Siemens, Allen-Bradley, Mitsubishi, Delta, Schneider</li></ul><h4>Applications:</h4><ul><li>Conveyor belt control</li><li>Automatic bottle filling</li><li>Traffic light control</li><li>Motor sequential starting</li></ul>'
  },
  { id:'energy-meter', title:'Energy Meter & Billing', titleHi:'एनर्जी मीटर और बिलिंग', description:'Types of meters, tariff, reading', descHi:'मीटर के प्रकार, टैरिफ, रीडिंग', topicId:'energy-meter', videoUrl:'', pdfUrl:'', imageUrl:'',
    notes:'<h3>📊 Energy Meter & Billing</h3><h4>Types of Energy Meters:</h4><ul><li><b>Electromechanical (disc type):</b> Rotating disc, older type</li><li><b>Electronic/Digital:</b> LCD display, accurate</li><li><b>Smart Meter:</b> Remote reading, prepaid option</li><li><b>CT-operated:</b> For high current loads</li></ul><h4>Energy Calculation:</h4><p><b>Energy (kWh) = Power (kW) × Time (hours)</b></p><p>1 Unit = 1 kWh</p><h4>Example:</h4><p>5 bulbs of 100W used for 10 hours:<br>Energy = 5 × 100 × 10 = 5000 Wh = <b>5 kWh = 5 Units</b></p><h4>Tariff Types:</h4><ul><li>Flat rate: Fixed price per unit</li><li>Telescopic/Slab: Price varies by consumption</li><li>ToD (Time of Day): Different rates for peak/off-peak</li></ul><h4>Power Factor Penalty:</h4><p>If PF < 0.85, extra charges apply. Improve PF using capacitor banks.</p>'
  },
  { id:'solar-energy', title:'Solar Energy Systems', titleHi:'सौर ऊर्जा प्रणाली', description:'Solar panels, inverters, installation', descHi:'सोलर पैनल, इनवर्टर, स्थापना', topicId:'solar-energy', videoUrl:'', pdfUrl:'', imageUrl:'',
    notes:'<h3>☀️ Solar Energy Systems</h3><h4>Solar Cell:</h4><p>Converts sunlight to electricity (photovoltaic effect). Made of silicon. Single cell = ~0.5V.</p><h4>Types of Solar Panels:</h4><ul><li><b>Monocrystalline:</b> High efficiency (20-22%), expensive</li><li><b>Polycrystalline:</b> Medium efficiency (15-17%), affordable</li><li><b>Thin Film:</b> Low efficiency, flexible</li></ul><h4>System Components:</h4><ol><li><b>Solar Panel:</b> Generates DC power</li><li><b>Charge Controller:</b> MPPT or PWM, protects battery</li><li><b>Battery Bank:</b> Stores energy for night use</li><li><b>Inverter:</b> Converts DC to AC (230V)</li></ol><h4>Types of Solar Systems:</h4><ul><li><b>On-Grid:</b> Connected to power grid, net metering</li><li><b>Off-Grid:</b> Standalone with battery backup</li><li><b>Hybrid:</b> Grid + Battery</li></ul><h4>Sizing Example:</h4><p>1 kW system needs: ~4 panels (250W each), ~100 sq ft roof area, generates ~4-5 units/day</p>'
  },
];
